#include "su4.h"
#include <array>
#include <iostream>

/*
    TESTED: 9th March.
    Something strange is happening over the move constructor (it's not called when I try to
    initialise su4::Vector from an rvalue, e.g. from the result of a summation). And instead somethng else
    is actually called, it might be an implicit move constructor generated by the compiler, I don't know.
    But anyways the class works properly.
*/

int main()
{
    std::array<double, 15> tmp1 = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
    std::array<double, 15> tmp2 = {5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33};
 
    su4::Vector vecZeros;
    su4::Vector vec1(tmp1);
    su4::Vector vec2(tmp2);
    su4::Vector vec3(vec1);
    su4::Vector vec4 = su4::Vector(tmp1);

    su4::Vector vec5; vec5 = vec1;
    su4::Vector vec6; vec6 = vec2 + vec3;
    su4::Vector vec7 = vec2 - vec3;
    su4::Vector vec8 = vec2*2.0;
    su4::Vector vec9 = 2.0*vec2;
    su4::Vector vec10 = vec2/2.0;
    su4::Vector vec11(vec1); vec11 += vec2;

    std::cout << "vecZeroes = "<< vecZeros << std::endl;
    std::cout << "vec1 = "<< vec1 << std::endl;
    std::cout << "vec2 = "<< vec2 << std::endl;
    std::cout << "vec3 = "<< vec3 << std::endl;
    std::cout << "vec4 = "<< vec4 << std::endl;
    std::cout << "vec5 = "<< vec5 << std::endl;
    std::cout << "vec6 = "<< vec6 << std::endl;
    std::cout << "vec7 = "<< vec7 << std::endl;
    std::cout << "vec8 = "<< vec8 << std::endl;
    std::cout << "vec9 = "<< vec9 << std::endl;
    std::cout << "vec10 = "<< vec10 << std::endl;
    std::cout << "vec11 = "<< vec11 << std::endl;

    return 0;
}